FROM python:3

WORKDIR /usr/src/app

RUN python --version

COPY ./deploy/requirements.ci ./
RUN pip install --no-cache-dir -r requirements.ci

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

ENTRYPOINT [ "./deploy/dev-entry.sh" ]
