version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: production_nginx
        volumes:
            - ./nginx/mancala.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
    mancala:
        build:
            context: .
            dockerfile: Dockerfile.api
        expose:
            - "5000"
