#!/bin/sh

# Create Python App
# by Mnebuerquo
# https://github.com/mnebuerquo/create-python-app
# Please keep the above link in place if you are using this in your project!

# This script builds your project into a docker image. It is called
# automatically when you try to run python, pip, or test the first time. You
# can run it at any time to ensure your image has all your requirements.txt
# dependencies installed.

. ./mn_image

if [ ! -f .env ]; then
	touch .env
fi

if [ ! -f requirements.txt ]; then
	echo "pytest-watch" >> requirements.txt
	echo "flake8" >> requirements.txt
fi

docker kill "$CONTAINER"
docker rmi "$IMAGE"
docker build -f "mn_Dockerfile" -t "$IMAGE" .
