#!/bin/sh

# Create Python App
# by Mnebuerquo
# https://github.com/mnebuerquo/create-python-app 
# Please keep the above link in place if you are using this in your project!

# This script runs python-test-watch for running pytest whenever one of your
# files changes.

. ./mn_image "$(basename $0)"

./mn_run flake8 --append-config=flake8.ini
